### ISSUE TITLE
Is is possible to use this library to change the REQUEST before to be sent to proxy?

### ISSUE THREAD

**Issue by macscripter** [philippotto/transformer-proxy#5]
Hello!
Is is possible to use this library to change the REQUEST before to be sent to proxy?
What I need is to add a new tag in the original request to proxy it.

Thank you!

var http = require('http'),
    httpProxy = require('http-proxy');

//
// Create a proxy server with custom application logic
//
var proxy = httpProxy.createProxyServer({});

//
// Create your custom server and just call `proxy.web()` to proxy
// a web request to the target passed in the options
// also you can use `proxy.ws()` to proxy a websockets request
//
var server = http.createServer(function(req, res) {
  // You can define here your custom logic to handle the request
  // and then proxy the request.
  proxy.web(req, res, { target: 'http://127.0.0.1:5060' });
});

console.log("listening on port 5050")
server.listen(5050);

**Comment by guumaster** [comment]
What you need can be done directly with `http-proxy`. Have you tried something like this?

```
proxy.on('proxyReq', function(proxyReq, req, res, options) {
  proxyReq.setHeader('X-my-tag', 'foobar');
});
```

**Comment by macscripter** [comment]
yeah! Already resolved!

Thanks!

Best regards

2016-03-26 15:04 GMT+00:00 Gustavo notifications@github.com:

**Comment by guumaster** [comment]
Ok. You can post your solution and close the issue? Thanks!

**Comment by droidrcc** [comment]
@macscripter Could you please share your solution?
Thanks
