### ISSUE TITLE
Issue with transformerFunction

### ISSUE THREAD

**Issue by volodymyr-tsaryk** [philippotto/transformer-proxy#6]
Hi,
On your examples data in transformer function is a string, however when I am getting it, it is a Buffer object, please refer screenshot for more details http://take.ms/7a3jn

Could you please help me with this issue ?

**Comment by philippotto** [comment]
Hi! Can you call toString on the buffer?

Volodymyr Tsaryk notifications@github.com schrieb am Mi., 9. Nov. 2016,
10:09:

**Comment by volodymyr-tsaryk** [comment]
It has that method, but doesn't work if i return string
However with another server when i return sting it works fine, that is quite weird
Working server uses Apache, non working uses nginx

**Comment by volodymyr-tsaryk** [comment]
Issue was related to GZIP, fixed like described here https://github.com/nodejitsu/node-http-proxy/issues/795

**Comment by kilobyte2007** [comment]
Has anyone managed to fix this while still keeping gzip? Disabling gzip slows down the proxy and the ultimate page drastically so it isn't really a solution. I've tried decoding the data with zlib but it seems that the Buffer arrives kind of broken already.
