### ISSUE TITLE
please update stream version to 0.0.2

### ISSUE THREAD

**Issue by attila123** [philippotto/transformer-proxy#9]
Hi,
transformer-proxy apparently uses stream@0.0.1. The problem is that in 0.0.1 they use the mocha as dependency, not devDependency. And mocha pulls in a lot of dependencies, you can check that with 'npm view', see below. They fixed this problem in stream@0.0.2, so please, please, please update to that and release a new version of transformer-proxy.

```
└─┬ transformer-proxy@0.3.3
  ├─┬ promise@7.1.1
  │ └── asap@2.0.5
  ├─┬ stream@0.0.1
  │ ├── expect.js@0.3.1
  │ └─┬ mocha@3.3.0
  │   ├── browser-stdout@1.3.0
  │   ├── commander@2.9.0 deduped
  │   ├─┬ debug@2.6.0
  │   │ └── ms@0.7.2
  │   ├── diff@3.2.0
  │   ├── escape-string-regexp@1.0.5 deduped
  │   ├── glob@7.1.1 deduped
  │   ├── growl@1.9.2
  │   ├── json3@3.3.2
  │   ├─┬ lodash.create@3.1.1
  │   │ ├─┬ lodash._baseassign@3.2.0
  │   │ │ ├── lodash._basecopy@3.0.1
  │   │ │ └─┬ lodash.keys@3.1.2
  │   │ │   ├── lodash._getnative@3.9.1
  │   │ │   ├── lodash.isarguments@3.1.0
  │   │ │   └── lodash.isarray@3.0.4
  │   │ ├── lodash._basecreate@3.0.3
  │   │ └── lodash._isiterateecall@3.0.9
  │   ├─┬ mkdirp@0.5.1
  │   │ └── minimist@0.0.8
  │   └─┬ supports-color@3.1.2
  │     └── has-flag@1.0.0
  └── util@0.10.3 deduped
```

The biggest for us is that a security scanner tool finds a vulnerability regarding growl@1.9.2 (pulled in by mocha): https://github.com/tj/node-growl/issues/60

**Comment by attila123** [comment]
Wow, that was a really quick turnaround, thanks! Looking for the new npm version of transformer-proxy.
Have a nice weekend! :)

**Comment by philippotto** [comment]
Thanks, have a nice weekend as well! The new version is published now.

**Comment by attila123** [comment]
Thank you very much!
World made better today: done :D
